### ISSUE TITLE
Use semantic HTML comparison instead of raw text/string comparison

### ISSUE THREAD

**Issue by egil** [SimonCropp/Verify#60]
#### Feature
HTML can change from a raw markup perspective, without changing the semantic meaning of it. Most common is changes to whitespace. This causes tests to break, when they do not need to.

#### Describe the solution
If Verify uses a semantic HTML comparison library, I created [AngleSharp Diffing](https://github.com/AngleSharp/AngleSharp.Diffing) for this exact purpose, instead of just doing text comparison, then tests that uses Verify will be much more stable. There are some additional options that can be used in to modify the diffing, e.g. switch to case insensitive comparison, or ignore certain attributes (generated IDs), that are also very helpful.

I will be happy to help integrate AngleSharp Diffing into Verify. Just let me know if you have any questions.

#### Additional context
The context is primarily with the bUnit integration. 

Here is a [quick sample](https://github.com/egil/BunitVerifySample), that shows how Verify fails a test because of insignificant whitespace, and the bUnit tests passes, because it uses `MarkupMatches` to verify the rendered markup, using AngleSharp Diffing.

**Comment by SimonCropp** [comment]
so the reason for not supporting this is complex. imagine the following scenario

 * you have a verified file
 * a change happens that results in attribute order change, it passes since it is technically equivalent
 * a change happens that results in different whitespace, it passes since it is technically equivalent
 * a change happens that results in singe to double quotes, it passes since it is technically equivalent
 * now a real change. it fails verification, now in the diff the UI show all the changes, not just the one that actual caused the failure.

There are several approaches to handling fragile test

 * keep them fragile. this might seems strange, bug using verify the friction of fragile tests is reduces since it is a single command line to accept a change. it really depends on how fragile the test is
 * use a [Scrubber](https://github.com/SimonCropp/Verify/blob/master/docs/scrubbers.md) to clean the result before verification. 
 * mark the test as [AutoVerify](https://github.com/SimonCropp/Verify/#autoverify) so that any change passes, and you instead rely on your diff tooling to highlight the change.

are any of the above viable for your scenario?

**Comment by egil** [comment]
Ok, I get that. Your library uses a differ to help the user show what is different. 

In bUnit, when users use the MarkupMatches to compare two snippets of html, I print out the actual semantic list of differences that AngleSharp Diffing provides. I also print out the actual and expected html, but I do pretty print/normalize them before doing so. I'll update this comment with an example later (typing from my phone) 

That, to me, mitigates the real issues you are highlighting above.

Another benefit with AngleSharp Diffing is that you allow the users to control the diffing process, e.g. ignoring parts like generated IDs, that can be different each time the tests are run. 

With all that, I do understand _if_ you want to keep everything consistent, and popup a diff tool every time there is a difference, then I get why you would not want to change things.

**Comment by egil** [comment]
Now that I think of it, the output from AngleSharp Diffing can be used to generate the merge error strings that we get when a merge fails (https://git-scm.com/docs/git-merge#_how_conflicts_are_presented). That would take everything to the next level. Verify users would still have to be aware why only parts are highlighted.

**Comment by SimonCropp** [comment]
i think this should meet your requirements https://github.com/SimonCropp/Verify.AngleSharp.Diffing
